"""Runtime config helpers for cidaren."""

from __future__ import annotations

import json
import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = BASE_DIR / ".env"

CONFIG_FIELDS = [
    "USERTOKEN",
    "ABC",
    "AUTH_V",
    "LLM_URL",
    "LLM_KEY",
    "LLM_MODEL",
]

DEFAULT_CONFIG = {
    "USERTOKEN": "",
    "ABC": "",
    "AUTH_V": "",
    "LLM_URL": "https://ai.saurlax.com/",
    "LLM_KEY": "",
    "LLM_MODEL": "step-3.6",
}

REQUIRED_AUTH_FIELDS = ("USERTOKEN", "ABC", "AUTH_V")


def _parse_env_value(raw: str) -> str:
    value = raw.strip()
    if not value:
        return ""
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        try:
            return json.loads(value) if value[0] == '"' else value[1:-1]
        except Exception:
            return value[1:-1]
    return value


def _format_env_value(value: str) -> str:
    if value is None:
        value = ""
    value = str(value)
    if value == "":
        return '""'
    if any(ch.isspace() for ch in value) or any(ch in value for ch in '#"\\'):
        return json.dumps(value, ensure_ascii=False)
    return value


def load_env_file() -> dict[str, str]:
    if not ENV_FILE.exists():
        return {}
    data: dict[str, str] = {}
    for raw_line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip().removeprefix("export ").strip()
        if not key:
            continue
        data[key] = _parse_env_value(value)
    return data


def get_runtime_config() -> dict[str, str]:
    config = dict(DEFAULT_CONFIG)
    config.update(load_env_file())
    for key in CONFIG_FIELDS:
        if key in os.environ:
            config[key] = os.environ[key]
    return config


def save_runtime_config(payload: dict[str, object]) -> dict[str, str]:
    current = load_env_file()
    for key in CONFIG_FIELDS:
        if key not in payload:
            continue
        value = payload.get(key, "")
        current[key] = "" if value is None else str(value).strip()

    merged = dict(DEFAULT_CONFIG)
    merged.update(current)

    lines = [
        "# cidaren runtime config",
        "# Generated by Web 控制台，按需修改即可。",
        "",
        "# 词达人鉴权",
    ]
    for key in REQUIRED_AUTH_FIELDS:
        lines.append(f"{key}={_format_env_value(merged.get(key, ''))}")

    lines.extend([
        "",
        "# LLM 兜底",
        f"LLM_URL={_format_env_value(merged.get('LLM_URL', ''))}",
        f"LLM_KEY={_format_env_value(merged.get('LLM_KEY', ''))}",
        f"LLM_MODEL={_format_env_value(merged.get('LLM_MODEL', ''))}",
        "",
    ])

    ENV_FILE.write_text("\n".join(lines), encoding="utf-8")
    for key in CONFIG_FIELDS:
        os.environ[key] = merged.get(key, DEFAULT_CONFIG.get(key, ""))
    return merged


def get_missing_auth_fields(config: dict[str, str] | None = None) -> list[str]:
    cfg = config or get_runtime_config()
    return [key for key in REQUIRED_AUTH_FIELDS if not (cfg.get(key) or "").strip()]


def build_subprocess_env(config: dict[str, str] | None = None) -> dict[str, str]:
    cfg = config or get_runtime_config()
    env = os.environ.copy()
    for key in CONFIG_FIELDS:
        env[key] = cfg.get(key, DEFAULT_CONFIG.get(key, ""))
    return env


def env_file_path() -> str:
    return str(ENV_FILE)
