from mitmproxy import http
import os
import sys


class TokenCatcher:
    def __init__(self):
        self.token_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".env")
        self.captured = {"USERTOKEN": False, "ABC": False, "AUTH_V": False}

    def response(self, flow: http.HTTPFlow):
        if flow.request.host != "app.vocabgo.com":
            return

        headers = flow.request.headers
        token = headers.get("UserToken")
        abc = headers.get("abc")
        auth_v = headers.get("authorization-v")

        if token and not self.captured["USERTOKEN"]:
            self.captured["USERTOKEN"] = True
            print(f"\n[OK] USERTOKEN: {token[:20]}...")

        if abc and not self.captured["ABC"]:
            self.captured["ABC"] = True
            print(f"[OK] ABC: {abc[:20]}...")

        if auth_v and not self.captured["AUTH_V"]:
            self.captured["AUTH_V"] = True
            print(f"[OK] AUTH_V: {auth_v[:20]}...")

        if token or abc or auth_v:
            self._save_to_env(token, abc, auth_v)

        if all(self.captured.values()):
            print("\n[OK] All tokens captured! You can close this window.")
            print(f"[OK] Saved to: {os.path.abspath(self.token_file)}")

    def _save_to_env(self, token, abc, auth_v):
        existing = {}
        if os.path.exists(self.token_file):
            with open(self.token_file, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#") or "=" not in line:
                        continue
                    key, value = line.split("=", 1)
                    key = key.strip().removeprefix("export ").strip()
                    if key:
                        existing[key] = value.strip()

        if token:
            existing["USERTOKEN"] = token
        if abc:
            existing["ABC"] = abc
        if auth_v:
            existing["AUTH_V"] = auth_v

        lines = [
            "# cidaren runtime config",
            "# Auto-generated by token catcher",
            "",
            "# 词达人鉴权",
        ]
        for key in ["USERTOKEN", "ABC", "AUTH_V"]:
            value = existing.get(key, "")
            if value and not (len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}):
                value = f'"{value}"'
            lines.append(f"{key}={value}")

        lines.extend([
            "",
            "# LLM 兜底",
            f"LLM_URL={existing.get('LLM_URL', '\"\"')}",
            f"LLM_KEY={existing.get('LLM_KEY', '\"\"')}",
            f"LLM_MODEL={existing.get('LLM_MODEL', '\"\"')}",
            "",
        ])

        with open(self.token_file, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))


addons = [TokenCatcher()]
